2022-03-13 14:30:14,704 ERROR bidi.py line+670 _thread_main [Thread-ConsumeBidirectionalStream]: Thread-ConsumeBidirectionalStream caught unexpected exception Process() missing 1 required positional argument: 'ticket' and will exit.
Traceback (most recent call last):
  File "/home/hiro/.local/lib/python3.8/site-packages/google/api_core/bidi.py", line 657, in _thread_main
    self._on_response(response)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 456, in on_snapshot
    meth(self, proto.target_change)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 381, in _on_snapshot_target_change_no_change
    self.push(target_change.read_time, target_change.resume_token)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 556, in push
    self._snapshot_callback(keys, appliedChanges, read_time)
  File "/home/hiro/Documents/Desarrollo/POS/pos-print-server/TicketDb.py", line 28, in on_snapshot
    self.callbackFn(ticket)
TypeError: Process() missing 1 required positional argument: 'ticket'
2022-03-15 12:05:03,445 ERROR bidi.py line+670 _thread_main [Thread-ConsumeBidirectionalStream]: Thread-ConsumeBidirectionalStream caught unexpected exception Process() missing 1 required positional argument: 'ticket' and will exit.
Traceback (most recent call last):
  File "/home/hiro/.local/lib/python3.8/site-packages/google/api_core/bidi.py", line 657, in _thread_main
    self._on_response(response)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 456, in on_snapshot
    meth(self, proto.target_change)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 381, in _on_snapshot_target_change_no_change
    self.push(target_change.read_time, target_change.resume_token)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 556, in push
    self._snapshot_callback(keys, appliedChanges, read_time)
  File "/home/hiro/Documents/Desarrollo/POS/pos-print-server/TicketDb.py", line 28, in on_snapshot
    self.callbackFn(ticket)
TypeError: Process() missing 1 required positional argument: 'ticket'
2022-03-15 13:11:07,677 ERROR bidi.py line+670 _thread_main [Thread-ConsumeBidirectionalStream]: Thread-ConsumeBidirectionalStream caught unexpected exception 'DocumentSnapshot' object has no attribute 'str' and will exit.
Traceback (most recent call last):
  File "/home/hiro/.local/lib/python3.8/site-packages/google/api_core/bidi.py", line 657, in _thread_main
    self._on_response(response)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 456, in on_snapshot
    meth(self, proto.target_change)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 381, in _on_snapshot_target_change_no_change
    self.push(target_change.read_time, target_change.resume_token)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 556, in push
    self._snapshot_callback(keys, appliedChanges, read_time)
  File "/home/hiro/Documents/Desarrollo/POS/pos-print-server/TicketDb.py", line 29, in on_snapshot
    print(ticket.str())
AttributeError: 'DocumentSnapshot' object has no attribute 'str'
2022-03-15 19:25:02,119 ERROR bidi.py line+670 _thread_main [Thread-ConsumeBidirectionalStream]: Thread-ConsumeBidirectionalStream caught unexpected exception 'DocumentSnapshot' object has no attribute 'user' and will exit.
Traceback (most recent call last):
  File "/home/hiro/.local/lib/python3.8/site-packages/google/api_core/bidi.py", line 657, in _thread_main
    self._on_response(response)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 456, in on_snapshot
    meth(self, proto.target_change)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 381, in _on_snapshot_target_change_no_change
    self.push(target_change.read_time, target_change.resume_token)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 556, in push
    self._snapshot_callback(keys, appliedChanges, read_time)
  File "/home/hiro/Documents/Desarrollo/POS/pos-print-server/TicketDb.py", line 28, in on_snapshot
    self.callbackFn(self, ticket)
  File "/home/hiro/Documents/Desarrollo/POS/pos-print-server/Ticket.py", line 6, in Process
    print(ticket.user.displayName)
AttributeError: 'DocumentSnapshot' object has no attribute 'user'
2022-03-15 19:25:54,538 ERROR bidi.py line+670 _thread_main [Thread-ConsumeBidirectionalStream]: Thread-ConsumeBidirectionalStream caught unexpected exception 'DocumentSnapshot' object has no attribute 'user' and will exit.
Traceback (most recent call last):
  File "/home/hiro/.local/lib/python3.8/site-packages/google/api_core/bidi.py", line 657, in _thread_main
    self._on_response(response)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 456, in on_snapshot
    meth(self, proto.target_change)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 381, in _on_snapshot_target_change_no_change
    self.push(target_change.read_time, target_change.resume_token)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 556, in push
    self._snapshot_callback(keys, appliedChanges, read_time)
  File "/home/hiro/Documents/Desarrollo/POS/pos-print-server/TicketDb.py", line 28, in on_snapshot
    self.callbackFn(self, ticket)
  File "/home/hiro/Documents/Desarrollo/POS/pos-print-server/Ticket.py", line 6, in Process
    print(ticket.user.displayName)
AttributeError: 'DocumentSnapshot' object has no attribute 'user'
2022-03-15 19:30:08,938 ERROR bidi.py line+670 _thread_main [Thread-ConsumeBidirectionalStream]: Thread-ConsumeBidirectionalStream caught unexpected exception 'DocumentSnapshot' object has no attribute 'data' and will exit.
Traceback (most recent call last):
  File "/home/hiro/.local/lib/python3.8/site-packages/google/api_core/bidi.py", line 657, in _thread_main
    self._on_response(response)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 456, in on_snapshot
    meth(self, proto.target_change)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 381, in _on_snapshot_target_change_no_change
    self.push(target_change.read_time, target_change.resume_token)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 556, in push
    self._snapshot_callback(keys, appliedChanges, read_time)
  File "/home/hiro/Documents/Desarrollo/POS/pos-print-server/TicketDb.py", line 28, in on_snapshot
    self.callbackFn(self, ticket)
  File "/home/hiro/Documents/Desarrollo/POS/pos-print-server/Ticket.py", line 6, in Process
    print(ticket.data())
AttributeError: 'DocumentSnapshot' object has no attribute 'data'
2022-03-15 19:33:25,148 ERROR bidi.py line+670 _thread_main [Thread-ConsumeBidirectionalStream]: Thread-ConsumeBidirectionalStream caught unexpected exception 'pirulo' and will exit.
Traceback (most recent call last):
  File "/home/hiro/.local/lib/python3.8/site-packages/google/api_core/bidi.py", line 657, in _thread_main
    self._on_response(response)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 456, in on_snapshot
    meth(self, proto.target_change)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 381, in _on_snapshot_target_change_no_change
    self.push(target_change.read_time, target_change.resume_token)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 556, in push
    self._snapshot_callback(keys, appliedChanges, read_time)
  File "/home/hiro/Documents/Desarrollo/POS/pos-print-server/TicketDb.py", line 28, in on_snapshot
    self.callbackFn(self, ticket.to_dict())
  File "/home/hiro/Documents/Desarrollo/POS/pos-print-server/Ticket.py", line 6, in Process
    print(ticket['pirulo'])
KeyError: 'pirulo'
2022-03-15 19:36:44,792 ERROR bidi.py line+670 _thread_main [Thread-ConsumeBidirectionalStream]: Thread-ConsumeBidirectionalStream caught unexpected exception 'dict' object has no attribute 'has_key' and will exit.
Traceback (most recent call last):
  File "/home/hiro/.local/lib/python3.8/site-packages/google/api_core/bidi.py", line 657, in _thread_main
    self._on_response(response)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 456, in on_snapshot
    meth(self, proto.target_change)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 381, in _on_snapshot_target_change_no_change
    self.push(target_change.read_time, target_change.resume_token)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 556, in push
    self._snapshot_callback(keys, appliedChanges, read_time)
  File "/home/hiro/Documents/Desarrollo/POS/pos-print-server/TicketDb.py", line 28, in on_snapshot
    self.callbackFn(self, ticket.to_dict())
  File "/home/hiro/Documents/Desarrollo/POS/pos-print-server/Ticket.py", line 6, in Process
    if ticket.has_key('user'):
AttributeError: 'dict' object has no attribute 'has_key'
2022-03-15 19:46:46,502 ERROR bidi.py line+670 _thread_main [Thread-ConsumeBidirectionalStream]: Thread-ConsumeBidirectionalStream caught unexpected exception unsupported operand type(s) for +: 'int' and 'str' and will exit.
Traceback (most recent call last):
  File "/home/hiro/.local/lib/python3.8/site-packages/google/api_core/bidi.py", line 657, in _thread_main
    self._on_response(response)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 456, in on_snapshot
    meth(self, proto.target_change)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 381, in _on_snapshot_target_change_no_change
    self.push(target_change.read_time, target_change.resume_token)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 556, in push
    self._snapshot_callback(keys, appliedChanges, read_time)
  File "/home/hiro/Documents/Desarrollo/POS/pos-print-server/TicketDb.py", line 28, in on_snapshot
    self.callbackFn(self, ticket.to_dict())
  File "/home/hiro/Documents/Desarrollo/POS/pos-print-server/Ticket.py", line 10, in Process
    print(item['quantity']+ "  "+ item['description'])
TypeError: unsupported operand type(s) for +: 'int' and 'str'
2022-03-15 23:48:36,281 ERROR bidi.py line+670 _thread_main [Thread-ConsumeBidirectionalStream]: Thread-ConsumeBidirectionalStream caught unexpected exception __init__() takes 2 positional arguments but 3 were given and will exit.
Traceback (most recent call last):
  File "/home/hiro/.local/lib/python3.8/site-packages/google/api_core/bidi.py", line 657, in _thread_main
    self._on_response(response)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 456, in on_snapshot
    meth(self, proto.target_change)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 381, in _on_snapshot_target_change_no_change
    self.push(target_change.read_time, target_change.resume_token)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 556, in push
    self._snapshot_callback(keys, appliedChanges, read_time)
  File "/home/hiro/Documents/Desarrollo/POS/pos-print-server/TicketDb.py", line 28, in on_snapshot
    self.callbackFn(self, ticket.to_dict())
  File "/home/hiro/Documents/Desarrollo/POS/pos-print-server/TicketProcessor.py", line 5, in process
    self.ticket = Ticket(self, ticket)
TypeError: __init__() takes 2 positional arguments but 3 were given
2022-03-15 23:49:23,734 ERROR bidi.py line+670 _thread_main [Thread-ConsumeBidirectionalStream]: Thread-ConsumeBidirectionalStream caught unexpected exception 'printAt' and will exit.
Traceback (most recent call last):
  File "/home/hiro/.local/lib/python3.8/site-packages/google/api_core/bidi.py", line 657, in _thread_main
    self._on_response(response)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 456, in on_snapshot
    meth(self, proto.target_change)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 381, in _on_snapshot_target_change_no_change
    self.push(target_change.read_time, target_change.resume_token)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 556, in push
    self._snapshot_callback(keys, appliedChanges, read_time)
  File "/home/hiro/Documents/Desarrollo/POS/pos-print-server/TicketDb.py", line 28, in on_snapshot
    self.callbackFn(self, ticket.to_dict())
  File "/home/hiro/Documents/Desarrollo/POS/pos-print-server/TicketProcessor.py", line 5, in process
    self.ticket = Ticket( ticket)
  File "/home/hiro/Documents/Desarrollo/POS/pos-print-server/Ticket.py", line 18, in __init__
    self.printAt=ticket[self.USER][self.PRINT_AT] if self.PRINT_AT in ticket else ""
KeyError: 'printAt'
2022-03-16 00:06:27,435 ERROR bidi.py line+670 _thread_main [Thread-ConsumeBidirectionalStream]: Thread-ConsumeBidirectionalStream caught unexpected exception __str__ returned non-string (type NoneType) and will exit.
Traceback (most recent call last):
  File "/home/hiro/.local/lib/python3.8/site-packages/google/api_core/bidi.py", line 657, in _thread_main
    self._on_response(response)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 456, in on_snapshot
    meth(self, proto.target_change)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 381, in _on_snapshot_target_change_no_change
    self.push(target_change.read_time, target_change.resume_token)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 556, in push
    self._snapshot_callback(keys, appliedChanges, read_time)
  File "/home/hiro/Documents/Desarrollo/POS/pos-print-server/TicketDb.py", line 28, in on_snapshot
    self.callbackFn(self, ticket.to_dict())
  File "/home/hiro/Documents/Desarrollo/POS/pos-print-server/TicketProcessor.py", line 8, in process
    print(self.ticket)
TypeError: __str__ returned non-string (type NoneType)
2022-03-16 00:07:08,657 ERROR bidi.py line+670 _thread_main [Thread-ConsumeBidirectionalStream]: Thread-ConsumeBidirectionalStream caught unexpected exception 'Ticket' object is not callable and will exit.
Traceback (most recent call last):
  File "/home/hiro/.local/lib/python3.8/site-packages/google/api_core/bidi.py", line 657, in _thread_main
    self._on_response(response)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 456, in on_snapshot
    meth(self, proto.target_change)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 381, in _on_snapshot_target_change_no_change
    self.push(target_change.read_time, target_change.resume_token)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 556, in push
    self._snapshot_callback(keys, appliedChanges, read_time)
  File "/home/hiro/Documents/Desarrollo/POS/pos-print-server/TicketDb.py", line 28, in on_snapshot
    self.callbackFn(self, ticket.to_dict())
  File "/home/hiro/Documents/Desarrollo/POS/pos-print-server/TicketProcessor.py", line 8, in process
    print(self.ticket())
TypeError: 'Ticket' object is not callable
2022-03-16 00:08:46,774 ERROR bidi.py line+670 _thread_main [Thread-ConsumeBidirectionalStream]: Thread-ConsumeBidirectionalStream caught unexpected exception __str__ returned non-string (type NoneType) and will exit.
Traceback (most recent call last):
  File "/home/hiro/.local/lib/python3.8/site-packages/google/api_core/bidi.py", line 657, in _thread_main
    self._on_response(response)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 456, in on_snapshot
    meth(self, proto.target_change)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 381, in _on_snapshot_target_change_no_change
    self.push(target_change.read_time, target_change.resume_token)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 556, in push
    self._snapshot_callback(keys, appliedChanges, read_time)
  File "/home/hiro/Documents/Desarrollo/POS/pos-print-server/TicketDb.py", line 28, in on_snapshot
    self.callbackFn(self, ticket.to_dict())
  File "/home/hiro/Documents/Desarrollo/POS/pos-print-server/TicketProcessor.py", line 8, in process
    print(str(self.ticket))
TypeError: __str__ returned non-string (type NoneType)
2022-03-16 00:40:56,157 ERROR bidi.py line+670 _thread_main [Thread-ConsumeBidirectionalStream]: Thread-ConsumeBidirectionalStream caught unexpected exception 'list' object has no attribute 'keys' and will exit.
Traceback (most recent call last):
  File "/home/hiro/.local/lib/python3.8/site-packages/google/api_core/bidi.py", line 657, in _thread_main
    self._on_response(response)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 456, in on_snapshot
    meth(self, proto.target_change)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 381, in _on_snapshot_target_change_no_change
    self.push(target_change.read_time, target_change.resume_token)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 556, in push
    self._snapshot_callback(keys, appliedChanges, read_time)
  File "/home/hiro/Documents/Desarrollo/POS/pos-print-server/TicketDb.py", line 28, in on_snapshot
    self.callbackFn(self, ticket.to_dict())
  File "/home/hiro/Documents/Desarrollo/POS/pos-print-server/TicketProcessor.py", line 5, in process
    self.ticket = Ticket( ticket)
  File "/home/hiro/Documents/Desarrollo/POS/pos-print-server/Ticket.py", line 20, in __init__
    for key in ticket[self.ITEMS].keys():
AttributeError: 'list' object has no attribute 'keys'
2022-03-16 00:45:49,696 ERROR bidi.py line+670 _thread_main [Thread-ConsumeBidirectionalStream]: Thread-ConsumeBidirectionalStream caught unexpected exception 'Ticket' object has no attribute 'items' and will exit.
Traceback (most recent call last):
  File "/home/hiro/.local/lib/python3.8/site-packages/google/api_core/bidi.py", line 657, in _thread_main
    self._on_response(response)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 456, in on_snapshot
    meth(self, proto.target_change)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 381, in _on_snapshot_target_change_no_change
    self.push(target_change.read_time, target_change.resume_token)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 556, in push
    self._snapshot_callback(keys, appliedChanges, read_time)
  File "/home/hiro/Documents/Desarrollo/POS/pos-print-server/TicketDb.py", line 28, in on_snapshot
    self.callbackFn(self, ticket.to_dict())
  File "/home/hiro/Documents/Desarrollo/POS/pos-print-server/TicketProcessor.py", line 5, in process
    self.ticket = Ticket( ticket)
  File "/home/hiro/Documents/Desarrollo/POS/pos-print-server/Ticket.py", line 23, in __init__
    self.items.append(__item)
AttributeError: 'Ticket' object has no attribute 'items'
2022-03-16 08:52:11,827 ERROR bidi.py line+670 _thread_main [Thread-ConsumeBidirectionalStream]: Thread-ConsumeBidirectionalStream caught unexpected exception 'int' object is not iterable and will exit.
Traceback (most recent call last):
  File "/home/hiro/.local/lib/python3.8/site-packages/google/api_core/bidi.py", line 657, in _thread_main
    self._on_response(response)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 456, in on_snapshot
    meth(self, proto.target_change)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 381, in _on_snapshot_target_change_no_change
    self.push(target_change.read_time, target_change.resume_token)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 556, in push
    self._snapshot_callback(keys, appliedChanges, read_time)
  File "/home/hiro/Documents/Desarrollo/POS/pos-print-server/TicketDb.py", line 28, in on_snapshot
    self.callbackFn(self, ticket.to_dict())
  File "/home/hiro/Documents/Desarrollo/POS/pos-print-server/TicketProcessor.py", line 8, in process
    for q in item.getQuantity():
TypeError: 'int' object is not iterable
2022-03-16 09:01:38,455 ERROR bidi.py line+670 _thread_main [Thread-ConsumeBidirectionalStream]: Thread-ConsumeBidirectionalStream caught unexpected exception 'int' object is not iterable and will exit.
Traceback (most recent call last):
  File "/home/hiro/.local/lib/python3.8/site-packages/google/api_core/bidi.py", line 657, in _thread_main
    self._on_response(response)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 456, in on_snapshot
    meth(self, proto.target_change)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 381, in _on_snapshot_target_change_no_change
    self.push(target_change.read_time, target_change.resume_token)
  File "/home/hiro/.local/lib/python3.8/site-packages/google/cloud/firestore_v1/watch.py", line 556, in push
    self._snapshot_callback(keys, appliedChanges, read_time)
  File "/home/hiro/Documents/Desarrollo/POS/pos-print-server/TicketDb.py", line 28, in on_snapshot
    self.callbackFn(self, ticket.to_dict())
  File "/home/hiro/Documents/Desarrollo/POS/pos-print-server/TicketProcessor.py", line 9, in process
    for q in item.getQuantity():
TypeError: 'int' object is not iterable
2022-03-20 13:48:43,768 ERROR bidi.py line+670 _thread_main [Thread-ConsumeBidirectionalStream]: Thread-ConsumeBidirectionalStream caught unexpected exception 'TicketDb' object has no attribute 'printRepo' and will exit.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/google/api_core/bidi.py", line 657, in _thread_main
    self._on_response(response)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 456, in on_snapshot
    meth(self, proto.target_change)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 381, in _on_snapshot_target_change_no_change
    self.push(target_change.read_time, target_change.resume_token)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 556, in push
    self._snapshot_callback(keys, appliedChanges, read_time)
  File "/home/pi/AJB/pos-print-server/TicketDb.py", line 24, in on_snapshot
    self.callbackFn(self, ticket.to_dict())
  File "/home/pi/AJB/pos-print-server/TicketProcessor.py", line 19, in process
    self.printRepo.PrintDoc( \
AttributeError: 'TicketDb' object has no attribute 'printRepo'
2022-03-20 19:23:53,232 ERROR bidi.py line+670 _thread_main [Thread-ConsumeBidirectionalStream]: Thread-ConsumeBidirectionalStream caught unexpected exception 'TicketDb' object has no attribute 'printDocMock' and will exit.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/google/api_core/bidi.py", line 657, in _thread_main
    self._on_response(response)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 456, in on_snapshot
    meth(self, proto.target_change)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 381, in _on_snapshot_target_change_no_change
    self.push(target_change.read_time, target_change.resume_token)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 556, in push
    self._snapshot_callback(keys, appliedChanges, read_time)
  File "/home/pi/AJB/pos-print-server/TicketDb.py", line 24, in on_snapshot
    self.callbackFn(self, ticket.to_dict())
  File "/home/pi/AJB/pos-print-server/TicketProcessor.py", line 25, in process
    self.printDocMock( \
AttributeError: 'TicketDb' object has no attribute 'printDocMock'
2022-03-23 08:29:18,096 ERROR bidi.py +670 _thread_main [Thread-ConsumeBidirectionalStream]: Thread-ConsumeBidirectionalStream caught unexpected exception 'TicketDb' object has no attribute 'printRepo' and will exit.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/google/api_core/bidi.py", line 657, in _thread_main
    self._on_response(response)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 456, in on_snapshot
    meth(self, proto.target_change)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 381, in _on_snapshot_target_change_no_change
    self.push(target_change.read_time, target_change.resume_token)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 556, in push
    self._snapshot_callback(keys, appliedChanges, read_time)
  File "/home/pi/AJB/pos-print-server/TicketDb.py", line 23, in on_snapshot
    self.callbackFn(self, ticket.to_dict())
  File "/home/pi/AJB/pos-print-server/TicketProcessor.py", line 20, in process
    self.printRepo.PrintDoc( \
AttributeError: 'TicketDb' object has no attribute 'printRepo'
2022-03-23 08:33:06,684 ERROR bidi.py +670 _thread_main [Thread-ConsumeBidirectionalStream]: Thread-ConsumeBidirectionalStream caught unexpected exception 'TicketDb' object has no attribute 'printRepo' and will exit.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/google/api_core/bidi.py", line 657, in _thread_main
    self._on_response(response)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 456, in on_snapshot
    meth(self, proto.target_change)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 381, in _on_snapshot_target_change_no_change
    self.push(target_change.read_time, target_change.resume_token)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 556, in push
    self._snapshot_callback(keys, appliedChanges, read_time)
  File "/home/pi/AJB/pos-print-server/TicketDb.py", line 23, in on_snapshot
    self.callbackFn(self, ticket.to_dict())
  File "/home/pi/AJB/pos-print-server/TicketProcessor.py", line 19, in process
    self.printRepo.PrintDoc( \
AttributeError: 'TicketDb' object has no attribute 'printRepo'
2022-03-23 08:53:30,798 ERROR bidi.py +670 _thread_main [Thread-ConsumeBidirectionalStream]: Thread-ConsumeBidirectionalStream caught unexpected exception process() takes 2 positional arguments but 3 were given and will exit.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/google/api_core/bidi.py", line 657, in _thread_main
    self._on_response(response)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 456, in on_snapshot
    meth(self, proto.target_change)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 381, in _on_snapshot_target_change_no_change
    self.push(target_change.read_time, target_change.resume_token)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 556, in push
    self._snapshot_callback(keys, appliedChanges, read_time)
  File "/home/pi/AJB/pos-print-server/TicketDb.py", line 23, in on_snapshot
    self.callbackFn(self, ticket.to_dict())
TypeError: process() takes 2 positional arguments but 3 were given
2022-03-23 08:55:48,536 ERROR bidi.py +670 _thread_main [Thread-ConsumeBidirectionalStream]: Thread-ConsumeBidirectionalStream caught unexpected exception process() takes 2 positional arguments but 3 were given and will exit.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/google/api_core/bidi.py", line 657, in _thread_main
    self._on_response(response)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 456, in on_snapshot
    meth(self, proto.target_change)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 381, in _on_snapshot_target_change_no_change
    self.push(target_change.read_time, target_change.resume_token)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 556, in push
    self._snapshot_callback(keys, appliedChanges, read_time)
  File "/home/pi/AJB/pos-print-server/TicketDb.py", line 23, in on_snapshot
    self.callbackFn(self, ticket.to_dict())
TypeError: process() takes 2 positional arguments but 3 were given
2022-03-23 08:59:05,655 ERROR bidi.py +670 _thread_main [Thread-ConsumeBidirectionalStream]: Thread-ConsumeBidirectionalStream caught unexpected exception process() takes 2 positional arguments but 3 were given and will exit.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/google/api_core/bidi.py", line 657, in _thread_main
    self._on_response(response)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 456, in on_snapshot
    meth(self, proto.target_change)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 381, in _on_snapshot_target_change_no_change
    self.push(target_change.read_time, target_change.resume_token)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 556, in push
    self._snapshot_callback(keys, appliedChanges, read_time)
  File "/home/pi/AJB/pos-print-server/TicketDb.py", line 23, in on_snapshot
    self.callbackFn(self, ticket.to_dict())
TypeError: process() takes 2 positional arguments but 3 were given
2022-03-23 09:00:06,351 ERROR bidi.py +670 _thread_main [Thread-ConsumeBidirectionalStream]: Thread-ConsumeBidirectionalStream caught unexpected exception can only concatenate str (not "DatetimeWithNanoseconds") to str and will exit.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/google/api_core/bidi.py", line 657, in _thread_main
    self._on_response(response)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 456, in on_snapshot
    meth(self, proto.target_change)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 381, in _on_snapshot_target_change_no_change
    self.push(target_change.read_time, target_change.resume_token)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 556, in push
    self._snapshot_callback(keys, appliedChanges, read_time)
  File "/home/pi/AJB/pos-print-server/TicketDb.py", line 23, in on_snapshot
    self.callbackFn( ticket.to_dict())
  File "/home/pi/AJB/pos-print-server/TicketProcessor.py", line 22, in process
    self.buildInvoice(ticketObj))
  File "/home/pi/AJB/pos-print-server/TicketProcessor.py", line 90, in buildInvoice
    "VENDEDOR:"+ticket.getDisplayName() + "          " + ticket.getPrintAt(),
TypeError: can only concatenate str (not "DatetimeWithNanoseconds") to str
2022-03-23 09:02:58,190 ERROR bidi.py +670 _thread_main [Thread-ConsumeBidirectionalStream]: Thread-ConsumeBidirectionalStream caught unexpected exception can only concatenate str (not "DatetimeWithNanoseconds") to str and will exit.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/google/api_core/bidi.py", line 657, in _thread_main
    self._on_response(response)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 456, in on_snapshot
    meth(self, proto.target_change)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 381, in _on_snapshot_target_change_no_change
    self.push(target_change.read_time, target_change.resume_token)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 556, in push
    self._snapshot_callback(keys, appliedChanges, read_time)
  File "/home/pi/AJB/pos-print-server/TicketDb.py", line 23, in on_snapshot
    self.callbackFn( ticket.to_dict())
  File "/home/pi/AJB/pos-print-server/TicketProcessor.py", line 22, in process
    self.buildInvoice(ticketObj))
  File "/home/pi/AJB/pos-print-server/TicketProcessor.py", line 90, in buildInvoice
    "VENDEDOR:"+ticket.getDisplayName() + "          " + ticket.getPrintAt(),
TypeError: can only concatenate str (not "DatetimeWithNanoseconds") to str
2022-03-27 10:51:44,843 ERROR bidi.py +670 _thread_main [Thread-ConsumeBidirectionalStream]: Thread-ConsumeBidirectionalStream caught unexpected exception cannot identify image file './p4.png' and will exit.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/google/api_core/bidi.py", line 657, in _thread_main
    self._on_response(response)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 456, in on_snapshot
    meth(self, proto.target_change)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 381, in _on_snapshot_target_change_no_change
    self.push(target_change.read_time, target_change.resume_token)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 556, in push
    self._snapshot_callback(keys, appliedChanges, read_time)
  File "/home/pi/AJB/pos-print-server/TicketDb.py", line 27, in on_snapshot
    self.callbackFn( ticket.to_dict())
  File "/home/pi/AJB/pos-print-server/TicketProcessor.py", line 19, in process
    self.printRepo.PrintDoc( \
  File "/home/pi/AJB/pos-print-server/PrintRepository.py", line 171, in PrintDoc
    self.printLine(line.getText(), alignment=line.getAlignment(), font=line.getFont(), size=line.getSize())
  File "/home/pi/AJB/pos-print-server/PrintRepository.py", line 152, in printLine
    self.prn.image( './p4.png')
  File "/usr/local/lib/python3.9/dist-packages/escpos/escpos.py", line 83, in image
    im = EscposImage(img_source)
  File "/usr/local/lib/python3.9/dist-packages/escpos/image.py", line 37, in __init__
    img_original = Image.open(img_source)
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 2958, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file './p4.png'
2022-03-27 17:10:03,784 ERROR bidi.py +670 _thread_main [Thread-ConsumeBidirectionalStream]: Thread-ConsumeBidirectionalStream caught unexpected exception can only concatenate str (not "NoneType") to str and will exit.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/google/api_core/bidi.py", line 657, in _thread_main
    self._on_response(response)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 456, in on_snapshot
    meth(self, proto.target_change)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 381, in _on_snapshot_target_change_no_change
    self.push(target_change.read_time, target_change.resume_token)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 556, in push
    self._snapshot_callback(keys, appliedChanges, read_time)
  File "/home/pi/AJB/pos-print-server/TicketDb.py", line 27, in on_snapshot
    self.callbackFn( ticket.to_dict())
  File "/home/pi/AJB/pos-print-server/TicketProcessor.py", line 22, in process
    self.buildInvoice(ticketObj))
  File "/home/pi/AJB/pos-print-server/TicketProcessor.py", line 90, in buildInvoice
    "VENDEDOR:"+ticket.getDisplayName() + "          " + str(ticket.getPrintAt()),
TypeError: can only concatenate str (not "NoneType") to str
2022-03-27 17:24:18,810 ERROR bidi.py +670 _thread_main [Thread-ConsumeBidirectionalStream]: Thread-ConsumeBidirectionalStream caught unexpected exception can only concatenate str (not "NoneType") to str and will exit.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/google/api_core/bidi.py", line 657, in _thread_main
    self._on_response(response)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 456, in on_snapshot
    meth(self, proto.target_change)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 381, in _on_snapshot_target_change_no_change
    self.push(target_change.read_time, target_change.resume_token)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 556, in push
    self._snapshot_callback(keys, appliedChanges, read_time)
  File "/home/pi/AJB/pos-print-server/TicketDb.py", line 27, in on_snapshot
    self.callbackFn( ticket.to_dict())
  File "/home/pi/AJB/pos-print-server/TicketProcessor.py", line 22, in process
    self.buildInvoice(ticketObj))
  File "/home/pi/AJB/pos-print-server/TicketProcessor.py", line 90, in buildInvoice
    "VENDEDOR:"+ticket.getDisplayName() + "          " + str(ticket.getPrintAt()),
TypeError: can only concatenate str (not "NoneType") to str
2022-03-27 18:00:22,059 ERROR bidi.py +670 _thread_main [Thread-ConsumeBidirectionalStream]: Thread-ConsumeBidirectionalStream caught unexpected exception can only concatenate str (not "NoneType") to str and will exit.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/google/api_core/bidi.py", line 657, in _thread_main
    self._on_response(response)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 456, in on_snapshot
    meth(self, proto.target_change)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 381, in _on_snapshot_target_change_no_change
    self.push(target_change.read_time, target_change.resume_token)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 556, in push
    self._snapshot_callback(keys, appliedChanges, read_time)
  File "/home/pi/AJB/pos-print-server/TicketDb.py", line 27, in on_snapshot
    self.callbackFn( ticket.to_dict())
  File "/home/pi/AJB/pos-print-server/TicketProcessor.py", line 22, in process
    self.buildInvoice(ticketObj))
  File "/home/pi/AJB/pos-print-server/TicketProcessor.py", line 90, in buildInvoice
    "VENDEDOR:"+ticket.getDisplayName() + "          " + str(ticket.getPrintAt()),
TypeError: can only concatenate str (not "NoneType") to str
2022-03-27 23:16:17,860 ERROR bidi.py +670 _thread_main [Thread-ConsumeBidirectionalStream]: Thread-ConsumeBidirectionalStream caught unexpected exception can only concatenate str (not "NoneType") to str and will exit.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/google/api_core/bidi.py", line 657, in _thread_main
    self._on_response(response)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 456, in on_snapshot
    meth(self, proto.target_change)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 381, in _on_snapshot_target_change_no_change
    self.push(target_change.read_time, target_change.resume_token)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 556, in push
    self._snapshot_callback(keys, appliedChanges, read_time)
  File "/home/pi/AJB/pos-print-server/TicketDb.py", line 27, in on_snapshot
    self.callbackFn( ticket.to_dict())
  File "/home/pi/AJB/pos-print-server/TicketProcessor.py", line 22, in process
    self.buildInvoice(ticketObj))
  File "/home/pi/AJB/pos-print-server/TicketProcessor.py", line 90, in buildInvoice
    "VENDEDOR:"+ticket.getDisplayName() + "          " + str(ticket.getPrintAt()),
TypeError: can only concatenate str (not "NoneType") to str
2022-03-27 23:19:51,433 ERROR bidi.py +670 _thread_main [Thread-ConsumeBidirectionalStream]: Thread-ConsumeBidirectionalStream caught unexpected exception can only concatenate str (not "NoneType") to str and will exit.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/google/api_core/bidi.py", line 657, in _thread_main
    self._on_response(response)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 456, in on_snapshot
    meth(self, proto.target_change)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 381, in _on_snapshot_target_change_no_change
    self.push(target_change.read_time, target_change.resume_token)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 556, in push
    self._snapshot_callback(keys, appliedChanges, read_time)
  File "/home/pi/AJB/pos-print-server/TicketDb.py", line 27, in on_snapshot
    self.callbackFn( ticket.to_dict())
  File "/home/pi/AJB/pos-print-server/TicketProcessor.py", line 22, in process
    self.buildInvoice(ticketObj))
  File "/home/pi/AJB/pos-print-server/TicketProcessor.py", line 90, in buildInvoice
    "VENDEDOR:"+ticket.getDisplayName() + "          " + str(ticket.getPrintAt()),
TypeError: can only concatenate str (not "NoneType") to str
2022-03-27 23:21:58,292 ERROR bidi.py +670 _thread_main [Thread-ConsumeBidirectionalStream]: Thread-ConsumeBidirectionalStream caught unexpected exception can only concatenate str (not "NoneType") to str and will exit.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/google/api_core/bidi.py", line 657, in _thread_main
    self._on_response(response)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 456, in on_snapshot
    meth(self, proto.target_change)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 381, in _on_snapshot_target_change_no_change
    self.push(target_change.read_time, target_change.resume_token)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 556, in push
    self._snapshot_callback(keys, appliedChanges, read_time)
  File "/home/pi/AJB/pos-print-server/TicketDb.py", line 27, in on_snapshot
    self.callbackFn( ticket.to_dict())
  File "/home/pi/AJB/pos-print-server/TicketProcessor.py", line 22, in process
    self.buildInvoice(ticketObj))
  File "/home/pi/AJB/pos-print-server/TicketProcessor.py", line 90, in buildInvoice
    "VENDEDOR:"+ticket.getDisplayName() + "          " + str(ticket.getPrintAt()),
TypeError: can only concatenate str (not "NoneType") to str
2022-03-28 00:31:57,448 ERROR bidi.py +670 _thread_main [Thread-ConsumeBidirectionalStream]: Thread-ConsumeBidirectionalStream caught unexpected exception 'Ticket' object has no attribute 'test' and will exit.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/google/api_core/bidi.py", line 657, in _thread_main
    self._on_response(response)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 456, in on_snapshot
    meth(self, proto.target_change)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 381, in _on_snapshot_target_change_no_change
    self.push(target_change.read_time, target_change.resume_token)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 556, in push
    self._snapshot_callback(keys, appliedChanges, read_time)
  File "/home/pi/AJB/pos-print-server/TicketDb.py", line 27, in on_snapshot
    self.callbackFn( ticket.to_dict())
  File "/home/pi/AJB/pos-print-server/TicketProcessor.py", line 19, in process
    if ticketObj.isTest():
  File "/home/pi/AJB/pos-print-server/Ticket.py", line 44, in isTest
    return self.test == True
AttributeError: 'Ticket' object has no attribute 'test'
2022-03-28 00:31:57,462 ERROR bidi.py +670 _thread_main [Thread-ConsumeBidirectionalStream]: Thread-ConsumeBidirectionalStream caught unexpected exception 'Ticket' object has no attribute 'test' and will exit.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/google/api_core/bidi.py", line 657, in _thread_main
    self._on_response(response)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 456, in on_snapshot
    meth(self, proto.target_change)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 381, in _on_snapshot_target_change_no_change
    self.push(target_change.read_time, target_change.resume_token)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 556, in push
    self._snapshot_callback(keys, appliedChanges, read_time)
  File "/home/pi/AJB/pos-print-server/TicketDb.py", line 27, in on_snapshot
    self.callbackFn( ticket.to_dict())
  File "/home/pi/AJB/pos-print-server/TicketProcessor.py", line 19, in process
    if ticketObj.isTest():
  File "/home/pi/AJB/pos-print-server/Ticket.py", line 44, in isTest
    return self.test == True
AttributeError: 'Ticket' object has no attribute 'test'
2022-03-28 00:33:51,406 ERROR bidi.py +670 _thread_main [Thread-ConsumeBidirectionalStream]: Thread-ConsumeBidirectionalStream caught unexpected exception 'Ticket' object has no attribute 'test' and will exit.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/google/api_core/bidi.py", line 657, in _thread_main
    self._on_response(response)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 456, in on_snapshot
    meth(self, proto.target_change)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 381, in _on_snapshot_target_change_no_change
    self.push(target_change.read_time, target_change.resume_token)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/firestore_v1/watch.py", line 556, in push
    self._snapshot_callback(keys, appliedChanges, read_time)
  File "/home/pi/AJB/pos-print-server/TicketDb.py", line 27, in on_snapshot
    self.callbackFn( ticket.to_dict())
  File "/home/pi/AJB/pos-print-server/TicketProcessor.py", line 19, in process
    if ticketObj.isTest():
  File "/home/pi/AJB/pos-print-server/Ticket.py", line 44, in isTest
    return self.test == True
AttributeError: 'Ticket' object has no attribute 'test'
